# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-flask-oidc.spec

issue_repository: https://github.com/fedora-infra/flask-oidc

# add or remove files that should be synced
files_to_sync:
    - python-flask-oidc.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: flask-oidc
# downstream (Fedora) RPM package name
downstream_package_name: python-flask-oidc

# dependencies needed to prepare for and build the source RPM
srpm_build_deps:
  - wget
  - poetry
  - curl
  - pytest

actions:
  post-upstream-clone:
    # fetch specfile from src.fp.o
    - "curl -o python-flask-oidc.spec https://src.fedoraproject.org/rpms/python-flask-oidc/raw/main/f/python-flask-oidc.spec"
    # Install Poetry
    - "sh -c 'curl -sSL https://install.python-poetry.org | python3 -'"
  get-current-version:
    # fetch the version number of the package from the setup.py file
    - "poetry version -s"
  create-archive:
      - "poetry build -f sdist"
      - "sh -c 'echo dist/flask_oidc-$(poetry version -s).tar.gz'"

jobs:
  # upon upstream PRs, perform COPR builds
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon upstream PRs, test builds
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon upstream releases, perform COPR builds
  - job: copr_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon upstream releases, test builds
  - job: tests
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon downstream changes, create a PR upstream with sync'd files from above
  - job: sync_from_downstream
    trigger: commit

  # land upstream release in fedora dist-git - no builds
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  # create an srpm from upstream and submit a scratch build to koji
  - job: production_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # downstream automation

  # trigger a build in koji for a new dist-git commit
  - job: koji_build
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  # create a new update in bodhi for a successful koji build. directly related to `koji_build`
  - job: bodhi_update
    trigger: commit
    metadata:
      dist_git_branches:
        # Don't create an update on Rawhide.
        - fedora-branched
