[tool.ruff]
select = ["E", "F", "W", "I", "B", "UP"]
line-length = 88
target-version = "py38"

[tool.ruff.per-file-ignores]
"tests/*" = ["S101", "S105", "S106"]
"doc/conf.py" = ["E402", "I001"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
