name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: fedorapython/fedora-python-tox:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        dnf install -y git python-devel python-tox
        pip install --upgrade poetry>=1.2.0
    - name: Mark the directory as safe for git
      run: git config --global --add safe.directory $PWD
    - name: Run Tests
      run: tox
